document.addEventListener("DOMContentLoaded", () => {
    const items = [
        { name: "あーね", description: "A word used when you understand or agree with what the other person is saying. It has a similar meaning to the Japanese 'naruhodo'." },
        { name: "朝活", description: "It refers to activities that make effective use of the morning hours. It mainly refers to using the time before work or school starts to engage in self-improvement, hobbies, exercise, or other activities." },
        { name: "朝シャン", description: "It is a Japanese slang term that refers to shampooing in the morning." },
        { name: "あざす", description: "It is an abbreviation of 'ありがとうございます' (thank you). It is commonly used among friends or in casual situations as a way to lightly express gratitude." },
        { name: "アツい", description: "Passionate: Used when a person or situation is very enthusiastic and passionate. For example, it can be used in phrases like 'アツいプレイ' or 'アツい試合.'  Amazing, cool: It is also used to mean something is very good, interesting, or worthy of attention. For example, 'アツいパフォーマンス'." },
        { name: "ありよりのあり", description: "It is an expression used to emphasize a positive nuance, meaning 'pretty good.'　'なしよりのあり' → More on the positive side (slightly affirmative).　'ありよりのなし' → More on the negative side (slightly negative).　'なしよりのなし' → Completely negative (absolutely not)." },
        { name: "家系", description: "Refers to a type of ramen known as 'iekei ramen.' It is a genre of ramen characterized by a rich pork bone soy sauce broth and thick straight noodles." },
        { name: "イカサマ", description: "A term that refers to cheating to manipulate results unfairly. It is especially used in the context of games or gambling, where a person tries to win through dishonest means." },
        { name: "イクメン", description: "It is a term combining '育児 (ikuji)' and 'メン (men),' referring to men who actively participate in raising children." },
        { name: "イケオジ", description: "It is an abbreviation for 'Iketeru Ojisan,' meaning a stylish and charming middle-aged man." },
        { name: "行けたら行く", description: "It is a phrase used to mean 'I'll go if I can' when responding to plans or invitations. It is often used when someone is invited or unsure about attending something. This phrase does not confirm attendance but rather expresses a flexible and vague stance. However, in many cases, the person does not actually go." },
        { name: "いじり", description: "Teasing or playing around.Jokingly teasing among friends." },
        { name: "いちきゅっぱ", description: "1980 yen is read as 'Ichi-kyu-happa.' 2980 yen is read as 'Ni-kyu-happa.'" },
        { name: "うぽつ", description: "It is an internet slang term that abbreviates 'アップロードお疲れさま！' It is mainly used on video-sharing sites (such as YouTube and Niconico) or social media to acknowledge newly uploaded videos or content." },
        { name: "えぐい", description: "Intense or extreme (can be both positive and negative)　Positive: 'この試合、えぐいプレーばっかりで興奮する!' (＝Amazing, overwhelming)Negative: 'この映画、グロくてえぐいシーン多かったわ...' (＝Too extreme, shocking)　2.Overwhelmingly great (mainly positive)'あの人の歌唱力、えぐいわ...' (＝Extremely impressive)　3.Mentally tough, shocking.'テストの点数、えぐいことになってた...' (＝Terrible, shocking)" },
        { name: "えもい", description: "'えもい' is a word that describes a state of mixed emotions, not just simple feelings of being moved. It can convey nostalgia, melancholy, beauty, and other deep emotions. It is widely used in various contexts, such as music, movies, landscapes, photos, and memories." },
        { name: "炎上", description: "It refers to a phenomenon, mainly on the internet, where a person, company, statement, or action receives criticism or backlash, leading to a surge of comments and widespread sharing." },
        { name: "おあいそ", description: "'おあいそ' is a casual expression used when requesting the bill at izakayas or casual dining establishments. In formal situations, it is better to use 'Okaikei onegaishimasu' (お会計お願いします)." },
        { name: "おけ", description: "It is a shortened slang term for 'OK.' Variations like 'おけまる' and 'おけまる水産' have the same meaning." },
        { name: "オタク", description: "It is a term used to refer to people who have a strong interest or deep passion for a specific hobby or field. Originally, it was often used for fans of anime, manga, and games, but nowadays, it is applied to a wide range of areas." },
        { name: "おつ", description: "It is a casual abbreviation of 'おつかれさま.' It is mainly used among friends or on the internet." },
        { name: "オワコン", description: "It is an internet slang term abbreviated from '終わったコンテンツ' , referring to something that was once popular but has now declined or faded away." },
        { name: "おん", description: "It is a more casual form of 'うん' (yes/affirmation) and is mainly used on internet forums and social media.　Example:「明日遊べる？」 → 「おん」（＝うん）" },
        { name: "ガチ", description: "It is a slang term meaning 'serious,' 'genuine,' or 'real.' Originally derived from 'ガチンコ' (a term for a serious match or contest), it has become widely used as youth slang and internet slang." },
        { name: "ガチャ", description: "It mainly refers to a lottery-based random selection system. Originally derived from capsule toy vending machines (Gachagacha/Gachapon), the term is now widely used in mobile games and online services." },
        { name: "カモ", description: "It is a slang term referring to a person who is easily taken advantage of or exploited for money. It has a negative connotation, so it should be used with caution." },
        { name: "ガラケー", description: "'ガラケー' is an abbreviation of 'Galapagos Keitai' (Galapagos mobile phone), referring to traditional mobile phones with flip designs and button-operated functions. It was used to describe feature phones before the widespread adoption of smartphones." },
        { name: "ガンギマリ", description: "Originally, it referred to a state of being high due to the influence of illegal drugs, but now it is used in a broader sense. Nowadays, it refers to being in a state of maximum excitement or being deeply engrossed in something, even without any connection to drugs." },
        { name: "カンスト", description: "It is a shortened term for 'counterstop,' referring to reaching the maximum limit of a game or value. It is primarily used as a gaming term but can also be applied in everyday conversation.「推しへの愛、カンストしてる！」（＝推しが好きすぎる）" },
        { name: "キュン死", description: "It is a youth slang and internet term meaning 'feeling a tightness in your chest, as if you might die from how precious or heart-fluttering something is.'" },
        { name: "キュンです", description: "It is a youth slang used when your heart flutters, often used in contexts like romance, supporting your favorite idols, or seeing something cute.　「この赤ちゃんの笑顔、キュンです」" },
        { name: "ギンギン", description: "It is used to describe a state of being full of vitality and energy.　「今日の試合、ギンギンに行こうぜ！」（＝今日は元気いっぱいにやろう！）" },
        { name: "グラサン", description: "It refers to sunglasses." },
        { name: "グロい", description: "It is a term mainly used to describe something 'disgusting,' 'unpleasant,' or 'grotesque.' It is particularly used for things that are visually uncomfortable or unsanitary." },
        { name: "合コン", description: "It is an abbreviation for '合同コンパ' (goudou konpa), referring to an event where men and women gather to interact. Typically, it is an occasion where multiple men and women come together with the goal of making friends or finding romantic connections, enjoying light meals or drinks while chatting." },
        { name: "G", description: "Another term for cockroach." },
        { name: "こたつむり", description: "It refers to the state of staying immobile while being cozy inside a kotatsu. This term is used mainly during the cold winter months to describe the situation of getting so comfortable in the kotatsu that you don’t feel like moving." },
        { name: "コミュ障", description: "It is an abbreviation for 'コミュニケーション障害(communication disorder),' referring to people who have difficulty with communication or are prone to feeling anxious in interpersonal relationships." },
        { name: "コミュ力", description: "It is an abbreviation for 'コミュニケーション力(communication skills),' referring to the ability to communicate smoothly with others and build good relationships." },
        { name: "ゴム", description: "It is a slang term for a condom." },
        { name: "コンビニ", description: "It is an abbreviation for 'convenience store,' referring to small-scale stores where you can easily purchase a variety of convenient products. Many of these stores are open 24 hours a day in Japan and offer a wide range of products and services, including food, daily necessities, magazines, drinks, bento, snacks, as well as ATM and delivery services. Major convenience store chains in Japan include 'Seven-Eleven (Seven),' 'Lawson,' 'FamilyMart (Famima),' 'Ministop,' and 'Daily Yamazaki.'" },
        { name: "サクラ", description: "It refers to a fake person created to attract others, such as a fake customer or applicant used for manipulation.　Example:「その合コン、サクラばっかりだった。」（＝'It was full of fake participants.'）" },
        { name: "サバサバ系", description: "It refers to a person with a straightforward personality and attitude, who doesn't show their emotions much. Generally, it is used to describe someone who is calm, positive, and has a simple, easygoing character." },
        { name: "サブスク", description: "It is an abbreviation for 'subscription,' referring to a system where you continue to use a service by paying a fixed fee. Typically, payments are made monthly or annually, and you can continue to use the service during the contract period." },
        { name: "サムい", description: "It is often used when a conversation or atmosphere feels awkward. Specifically, it is used when the mood has cooled down or when things didn’t go well and didn’t pick up.　Example:「今の話、ちょっとサムかったね」" },
        { name: "ジェネリック○○", description: "Originally, 'generic' was a term used in the pharmaceutical world. Simply put, it refers to products that contain the same ingredients and have the same effects as the original product but are offered at a lower cost. Recently, the term 'ジェネリック○○' has been used for products other than pharmaceuticals. For example, 'ジェネリック家電(generic electronics),' 'ジェネリック食品(generic food),' or 'ジェネリックコスメ(generic cosmetics)' are used when referring to products that are similar to the original ones." },
        { name: "しゃーなし", description: "It is a Japanese slang used to express 'it can't be helped' or 'there's nothing that can be done.' It is often used in situations where one is resigned or has to reluctantly accept something." },
        { name: "しゃしゃる", description: "The slang term '出しゃばる' refers to someone who oversteps their bounds by doing unnecessary things or taking actions that are too bold. It is used when someone interferes forcefully or excessively asserts themselves in a situation, disregarding their appropriate role or position." },
        { name: "しゃばい", description: "It means 'weak,' 'boring,' 'reliable,' or 'unsatisfactory.' Depending on the context, it can carry a negative nuance, such as something being disappointing or lacking in excitement." },
        { name: "地雷系", description: "'地雷系' is a term that uses '地雷' (land mines or explosives) as a metaphor, referring to people who have a personality or behavior that creates dangerous situations or requires caution. It is often used to describe individuals who tend to cause trouble in relationships, have extreme emotional fluctuations, and engage in unpredictable actions." },
        { name: "地雷", description: "'地雷' originally refers to an explosive device buried underground, which detonates when stepped on. However, in everyday conversation and slang, it is used metaphorically to refer to something that causes dangerous situations or problems. When used in the context of human relationships, it often describes a person or situation that, when touched or interacted with, is likely to lead to trouble or conflict." },
        { name: "しらばっくれる", description: "This Japanese expression refers to the act of pretending not to know about something you are involved in or something you have done, often to avoid responsibility or to lie your way out of a situation. It is commonly used to describe acts of evading accountability or making excuses." },
        { name: "二郎系", description: "'二郎系' refers to ramen that is inspired by the ramen restaurant 'ラーメン二郎.' ラーメン二郎 is famous for its large servings, often topped with a lot of pork, bean sprouts, and garlic, making it known for its immense volume. The term '二郎系' is used to describe ramen shops that mimic this style or ramen that features similar characteristics." },
        { name: "じわる", description: "This slang refers to a situation where humor or laughter gradually builds up. It describes the feeling when something becomes funnier over time, or when laughter slowly starts to surface. It’s often used when something starts off not being immediately funny but eventually grows on you and becomes more amusing." },
        { name: "すべる", description: "'すべる' is a Japanese slang that mainly means failing to get a laugh, not being funny, or making a mistake. It is often used in comedic situations or when a joke doesn't land, meaning that the humor or attempt at making people laugh didn't succeed." },
        { name: "スぺる", description: "It’s a slang term for getting injured, derived from the game Spelunker." },
        { name: "すっぴん", description: "It’s a Japanese term that refers to a face without makeup. It mainly refers to a woman’s natural, unmade-up face." },
        { name: "ケータイ", description: "A term referring to mobile phones, including smartphones." },
        { name: "それな", description: "A casual Japanese expression often used to mean 'Exactly' or 'I think so too.' It is used when agreeing with or empathizing with what someone else is saying." },
        { name: "大草原", description: "In internet slang, it is used to mean 'I laughed a lot' or 'I laughed so hard.' It is a way to express laughter when someone says something funny or when something unexpected happens. For example, it could be used like '大草原不可避'." },
        { name: "タメ", description: "It refers to speaking casually without using honorifics. It's a more informal way of talking, typically used with friends or close people. Also, 'タメ' can mean 'the same age,' so when you say 'タメの友達,' it means 'a friend of the same age.'" },
        { name: "チキる", description: "It is a slang mainly used among young people, meaning to get scared or to chicken out. It comes from the English word 'chicken' (meaning cowardly or scared). For example, if someone hesitates to take on a challenge or is too scared to do something, they might say 'チキる' (chikiru)." },
        { name: "チャリ", description: "It refers to a bicycle. It is also sometimes called 'チャリンコ.'" },
        { name: "廃人", description: "It is often used on the internet or among young people to refer to someone who has become so absorbed in a hobby or game that they are unable to lead a normal social or daily life. In other words, it describes a state of being excessively absorbed to the point where one can't live an ordinary life. However, it is often used lightly or self-deprecatingly.　Example:ツイ廃(ツイッター廃人)" },
        { name: "ツンデレ", description: "The term 'ツンデレ' refers to a character or personality that initially acts cold or indifferent, but later shows affection or kindness towards someone they actually like. This term is often used for characters in anime or manga, but it can also be seen in real-life relationships.　A 'tsundere' typically behaves coldly (acting 'ツンツン') at first, but later displays sweetness or affection ('デレデレ'). Tsundere characters are often shy or embarrassed, which makes it difficult for them to openly express their feelings." },
        { name: "夢の国", description: "The nickname for Disneyland." },
        { name: "デマ", description: "It refers to false or untrue information. It is often used to describe fake news or rumors that confuse people or cause misunderstandings. The phrase 'デマを流す' is also used, referring to the act of intentionally spreading false information." },
        { name: "チルい", description: "Derived from the English word 'chill,' it means 'to relax' or 'to calm down.' In Japanese, it is also casually used to mean 'spending time leisurely' or 'calming down.' It often implies a laid-back, relaxed state." },
        { name: "ドカ食い", description: "It refers to eating a large amount of food at once. This term is often used when someone who usually doesn't eat much suddenly eats too much, or when a person overeats in one sitting." },
        { name: "とちる", description: "This slang is mainly used in gaming or sports contexts and refers to making mistakes or failing at something. It is often used when someone loses focus or is off their game, resulting in failure. For example, in a game, saying 'とちった!' means 'I messed up!' or 'I failed!'" },
        { name: "ドッキリ", description: "This refers to a prank or setup intended to surprise or shock someone. It is especially common in TV shows, where people are caught off guard or placed in shocking situations without prior warning, and their reactions are captured for entertainment. In Japan, it is often referred to as 'ドッキリ企画' (dokiri kikaku) or 'ドッキリ映像' (dokiri eizō)." },
        { name: "ととのう", description: "A recent expression used in youth slang or internet slang that refers to something being organized or completed perfectly. It is often used when someone reaches a 'mentally calm state' or attains an 'ideal situation.'" },
        { name: "とりあえず生で", description: "A phrase often used in drinking or dining situations, particularly meaning 'let's start with a draft beer.' It signifies the common practice of ordering a draft beer first when starting a drinking session, and then deciding on other drinks or food afterward. The phrase 'とりあえず生で' (which translates to 'let's go with a draft beer for now') reflects the typical sequence in many social settings." },
        { name: "なんでやねん", description: "A Kansai dialect expression meaning 'How did this happen?' or 'Why is this happening?' It is used to express surprise, doubt, or to make a witty retort. This phrase is typically used when reacting to someone's actions or a situation that is surprising or unbelievable." },
        { name: "ナンパ", description: "This refers to the act of casually approaching someone of the opposite sex and trying to get closer to them. Generally, it is a lighthearted attempt to start a romantic or dating relationship. This behavior is often seen in places like streets, clubs, or bars, and sometimes it may not be very serious." },
        { name: "肉食系", description: "This term refers to someone who is proactive in romantic relationships or human interactions, and who actively takes the initiative to approach others. In the context of romance, it describes individuals who lead and make advances toward the other person with a more assertive attitude. The opposite term is '草食系' (soushoku-kei), which refers to people who are passive in romance and tend not to take the initiative in pursuing relationships." },
        { name: "ニート", description: "This term refers to young people who are neither receiving an education, working, nor undergoing vocational training. In Japan, it is often used to describe young people who are neither attending school, not involved in job hunting, nor working, essentially individuals who are inactive in terms of education and employment." },
        { name: "ニキ", description: "'ニキ' is a slang term used mainly in online spaces or among young people, and it's a shortened form of '兄貴' (aniki), which originally means 'older brother' or a respectful term for an older male. In casual conversations, it is sometimes used to refer to a close, older male friend or acquaintance in a friendly or informal way.'ニキ' can be used with a light tone, such as in phrases like 'ニキ、元気？' (How's it going, bro?) or 'お疲れニキ!' (Good job, bro!). The term is used among friends or people with close relationships.　For women, the counterpart is 'ネキ,' which comes from '姉貴' (aneki), the term for an older sister." },
        { name: "ニパチ", description: "'280 yen' is referred to as 'ニパチ' (ni-pachi) in Japanese slang. Similarly, '380 yen' is called 'サンパチ' (san-pachi)." },
        { name: "ネタバレ", description: "This refers to revealing key plot points or important information about a movie, drama, manga, or game to someone who has not yet experienced it. This can spoil the enjoyment of the work and take away the element of surprise, so 'spoilers' are generally something to avoid. For example, you might say, '映画のラストシーン、ネタバレしないで！' when asking someone not to reveal crucial details about the story." },
        { name: "飲み", description: "This is a slang term commonly used as an abbreviation for '飲み会'. It refers to social gatherings where friends, colleagues, or acquaintances drink alcohol or other beverages together. In casual conversation, it’s often used when inviting or suggesting going out for drinks, such as saying '飲み行こう！' or '飲み行きますか？'" },
        { name: "バグる", description: "This is a net slang derived from the English word 'bug,' and it refers to unexpected errors or glitches occurring in games or software. Specifically, when something in a program or game behaves abnormally or malfunctions, it’s referred to as 'バグる' in Japanese.　For example, 'ゲームがバグって進めない！' means 'The game is bugged, and I can't progress!'" },
        { name: "バズる", description: "'バズる' (buzuru) refers to something going viral or gaining rapid attention and popularity on social media or the internet. It often describes content like posts, videos, or memes that are shared or retweeted by a large number of people.　For example, if someone says, 'この動画、めっちゃバズってる！' , it means 'This video is going viral!' or 'This video is really popular and getting a lot of attention.'" },
        { name: "パチる", description: "The act of stealing something, commonly used in the Kansai region of Japan. For example, '消しゴムをパちる' means 'to steal an eraser.'" },
        { name: "パチンカス", description: "This term is used in a derogatory way to refer to people who are overly dependent on pachinko or slot machines, particularly those whose gambling habits negatively impact their lives or finances. The expression implies a disapproval of spending excessive time or money on pachinko, reflecting the harmful consequences of such addiction.　Similarly, for people addicted to cigarettes, the term 'ヤニカス' (Yanikasu) is used to mockingly refer to them." },
        { name: "ばっくれる", description: "This slang is primarily used to mean 'to escape' or 'to skip'. It refers to intentionally abandoning responsibility or running away from a situation where something must be done.　For example, if someone skips work or doesn't keep a promise, they can be described as having 'ばっくれた' (bakkureta). Similarly, saying '学校をばっくれる' means skipping school." },
        { name: "華金", description: "'華金' (pronounced 'Hanakin') is a Japanese term that refers to Friday night, specifically the time after work or school when the weekend begins. It focuses on the enjoyment and relaxation that comes with the start of the weekend.　In Japan, Friday night is often seen as the most relaxing time of the week, and it's common for people to go out with friends or colleagues to drink or have fun. The term '華金'  reflects the idea of enjoying this time to its fullest and making the most of the social opportunities it offers." },
        { name: "ハマる", description: "The term 'ハマる' (hamaru) refers to becoming deeply absorbed or obsessed with something, often in a positive sense. It describes a situation where someone becomes so engrossed or captivated by a hobby, activity, game, movie, music, or other interests that they lose track of time.　For example, if someone says they 'ハマる' on a particular game or anime, it means they are totally engrossed in it, enjoying it to the point where it becomes a major focus of their attention. It often conveys a sense of enthusiasm and passion for the subject." },
        { name: "バンドエイド", description: "The term 'Band-Aid' refers to adhesive bandages, also known as 'kizuteepu' (キズテープ) or 'cut ban' (カットバン) in Japanese. These are used to protect small wounds or cuts." },
        { name: "ピキる", description: "The slang 'ピキる' (pikiru) refers to a state where anger or frustration is about to explode, typically due to small or unexpected events. It describes the moment when emotions are reaching a peak, just before someone 'snaps' or 'loses their temper.'　For example, 'そんなことでピキるなよ！' means ’’Don't get angry over something like that!' or 'Don't let that get to you!'" },
        { name: "ブーメラン", description: "The slang 'ブーメラン' (boomerang) is used to describe a situation where someone's words or actions come back to affect them negatively later on. It refers to when someone criticizes or harms others, only for those actions or criticisms to be turned back on them.　For example, 'あの人、悪口を言ってたけど、まさにブーメランだね' means 'That person was talking badly about others, but it’s really a boomerang,' indicating that the criticism or bad behavior came back to haunt them." },
        { name: "腐女子", description: "'腐女子' (fujoshi) is a term primarily used to describe women who have a strong interest or affection for male-male romance or relationships, often in the 'BL' (Boys' Love) genre. BL refers to works that depict romantic relationships between male characters, and '腐女子' refers to women who are passionate about this genre, sometimes creating their own works or enjoying it with like-minded fans.　While the term '腐女子' originally carried a slightly negative connotation, it has become more widely embraced by many fans today, with many using it to describe themselves without concern." },
        { name: "太客", description: "'太客' (futokyaku) refers to customers who frequently spend large amounts of money, typically in businesses or service industries. This term is commonly used in restaurants, host clubs, or similar establishments to describe clients who make regular, high-value purchases, making them important to the business.　These 太客' customers are often given special treatment due to their significant contribution to the store's revenue." },
        { name: "ポイ活", description: "'ポイ活' (poikatsu) is short for 'ポイント活動' (point activities), referring to activities where individuals accumulate points through various methods and then utilize them. Common ways to earn points include making purchases on online stores, answering surveys, using apps, etc. Once accumulated, points can be exchanged for products, gift cards, or even cash.　For example, 'ポイ活' might involve earning points by using cashback offers while shopping, watching ads, or completing tasks, and then redeeming those points for items or cash." },
        { name: "ポテチ", description: "The abbreviation for 'potato chips' in Japanese" },
        { name: "ま？", description: "The word 'ま?' (ma?) is a casual expression used primarily among young people to express surprise or doubt. It is used when something unbelievable happens, and it conveys the meaning of 'Really?' or 'No way?'　　For example, if a friend tells you something unbelievable, saying 'ま?' shows that you're expressing surprise or doubt, asking 'Is it true?' or 'Are you serious?'" },
        { name: "マック", description: "'マクド' and 'マック' are abbreviations for 'マクドナルド' (McDonald's) in Japanese." },
        { name: "もち", description: "The abbreviation for 'もちろん' (of course) in Japanese, used in a positive context, is 'もち'." },
        { name: "モチベ", description: "The abbreviation for 'モチベーション' (motivation) in Japanese is 'モチベ'. It is used in contexts like '勉強のモチベが上がった' (My motivation for studying has increased)." },
        { name: "やばい", description: "'やばい' is a Japanese word with a wide range of meanings, depending on the context. It is mainly used in the following ways:　　Dangerous or Bad Situation: Originally, 'やばい' was used to describe something dangerous, problematic, or undesirable. 　For example, 'やばい、遅刻する！' (Oh no, I'm going to be late!) is used when something bad seems likely to happen.　　Positive Surprise or Impressed: It is now often used in a positive sense as well. For instance, 'この映画、やばいくらい面白かった！' (This movie was ridiculously good!) means that something was really impressive or amazing.　　Emphasis: It can be used to emphasize something that was unexpectedly great or impressive. For example, when something is surprisingly amazing, 'やばい!' is used to express intense emotion or surprise.　　Thus, depending on the situation, 'やばい' can have either a positive or negative meaning." },
        { name: "ラノベ", description: "'ラノベ' (Rano-be) is an abbreviation for 'ライトノベル' (light novel), referring to a genre of novels that are typically aimed at young readers. These novels are characterized by easy-to-read prose, often accompanied by illustrations in anime or manga style. The stories usually fall within genres such as fantasy, science fiction, or school life, and are known for their fast pace and simple, easy-to-understand narrative structure.　　Popular light novels are frequently adapted into anime or manga. Examples include 'Sword Art Online' and 'Re:Zero - Starting Life in Another World.'" },
        { name: "り", description: "'り' is a slang abbreviation for '了解' (ryoukai), which means 'understood' or 'got it' in Japanese. It is commonly used in casual conversations and on social media. " },
        { name: "リセマラ", description: "'リセマラ' is short for 'リセットマラソン' (Reset Marathon), which refers to a practice in mobile games or online games where a player resets their account multiple times to try and get a better result, typically from a gacha (a random draw or capsule-toy machine). The player keeps restarting the game and repeating the gacha pulls until they get ideal or rare characters, items, or rewards.　　For example, if you don’t get strong characters or items from the free gacha at the start of the game, you reset the account and try again." },
        { name: "ワロタ", description: "'ワロタ' is an internet slang term used to express laughter or find something funny. It originated from the word '笑った' (waratta), which means 'laughed,' but the pronunciation changed to 'ワロタ' to make it more casual and lighthearted. The term is often used in online communication, particularly in chat, forums, or social media.　　For example, when you see or hear something funny, you might write 'ワロタｗｗｗ,' with the 'ｗｗｗ' being a representation of laughter, similar to 'lol' or 'haha' in English." },
        { name: "意味深", description: "'意味深' (いみしん) literally means 'deep meaning,' but it is typically used to describe words or actions that seem to carry a hidden intention or deeper meaning. It is often used when someone makes vague or ambiguous statements, or when their true intent is unclear.　　For example, if someone says something that is not straightforward or leaves you wondering about their real meaning, you might say '意味深な発言' . 　　Example: 'あの人の発言、ちょっと意味深だね'." },
        { name: "遺伝子レベルで", description: "The expression '遺伝子レベルで違う'  is a metaphorical phrase that implies not just physical differences but also fundamental differences in aspects such as personality, thinking, or behavior. It suggests that the differences are so deep-rooted and intrinsic that they go beyond surface-level characteristics, almost as if they are part of a person's very essence or genetic makeup.　　Example: 「彼の才能は遺伝子レベルで優れている」" },
        { name: "一発屋芸人", description: "The term '一発屋'  refers to a comedian or entertainer in Japan who achieved a single, major hit or success but has not been able to maintain a significant presence or achieve further success after that." },
        { name: "陰キャ", description: "The term '陰キャ' (inkya) is a slang used primarily among young people in Japan to refer to someone who is introverted and tends to avoid being in the spotlight or interacting in social situations. The opposite of this term is '陽キャ' (yōkya), which refers to someone who is extroverted, sociable, and outgoing.　　Example:「あの子は陰キャだから、あまりパーティーには行かないよね」" },
        { name: "映え", description: "The term '映える' (haeru) is used mainly in the context of SNS or photography and means 'visually appealing' or 'looks good.' It refers to something that is aesthetically attractive, especially in photos or videos. The phrase 'インスタ映え' (Insta-baé) refers to a picture or post that is visually striking and likely to gain attention on social media platforms like Instagram." },
        { name: "塩顔", description: "A word that describes a person with sharp and refined facial features, giving off a cool and calm impression. It is often used for people with a sleek appearance that conveys a sense of kindness and delicacy." },
        { name: "塩対応", description: "'塩対応' means giving a cold or indifferent response. It describes someone being distant or unenthusiastic in their interaction.　　Example:「あの店員さん、ちょっと塩対応だったね」" },
        { name: "火の玉ストレート", description: "The phrase refers to expressing very direct and strong words or opinions without hesitation. It's used when someone wants to say exactly what they think in a straightforward manner. 　　Example:「彼の意見はいつも火の玉ストレートだね。遠慮せずに言いたいことを言ってる」" },
        { name: "界隈", description: "The term refers to a group or community within a specific field or area, or to the surrounding region or situation. It is commonly used to describe a gathering of people who share a common interest or belong to a particular community.　　Example:「最近、アニメ界隈では新しい作品が話題になっている」" },
        { name: "顔バレ", description: "The term '顔バレ'  refers to the situation where someone's face becomes known to others, especially in contexts where anonymity is maintained, such as on social media or online activities. It is commonly used when a person who has been operating anonymously, like a YouTuber or influencer, reveals their face, thereby exposing their identity. Many people who value their privacy may avoid this situation to prevent their online persona from being linked to their real-world identity.　　Example:「SNSで顔バレしたくないから、顔は絶対に載せない」" },
        { name: "既読スルー", description: "The term '既読無視' (kudoku mushi) refers to the act of reading a message without replying to it. This is particularly common in messaging apps like LINE, where the 'read' status shows that the recipient has seen the message, but they choose not to respond, leaving the message unattended.　　Example:「彼、昨日私のメッセージ見たけど、既読スルーだった」" },
        { name: "月９", description: "The term '月9' (Getsu-ku) refers to a television drama in Japan that airs every Monday night at 9:00 PM. Specifically, dramas in the 9:00 PM slot on Fuji TV are commonly referred to as '月9', and this time slot has been known for hosting highly popular dramas." },
        { name: "原点にして頂点", description: "The term means to embody both the beginning and the highest state, often used to praise something or someone." },
        { name: "限界社会人", description: "This term refers to adults who feel mentally or physically at their limit in their work or social life. It describes a state where various burdens such as overwork, stress, and interpersonal issues have piled up, leading to a sense of being overwhelmed. It is used to express a situation where daily tasks or life in general have become so difficult that the person feels they can no longer endure it.　　Example:「最近、仕事が忙しすぎて限界社会人になりかけてる」" },
        { name: "誤爆", description: "This term refers to sending an unintended message or post, especially on social media, chat apps, or forums. It is used when someone accidentally sends a message to the wrong recipient or mistakenly publishes something that should not have been shared publicly.　　For example, sending a private message to a group chat or posting something on the wrong account is referred to as '誤爆' (gobaku)." },
        { name: "最＆高", description: "It means 'the best'." },
        { name: "作画崩壊", description: "In anime and manga, this term refers to a sudden drop in the quality of artwork, causing character designs and animations to become distorted or inconsistent. It is often used when tight production schedules result in sloppy animation.　　For example, if a character's face or body proportions appear noticeably off or movements look unnatural, people might say, '作画崩壊だ!' " },
        { name: "事故", description: "This term refers to unexpected or unfortunate events. While it originally describes physical collisions, damage, or injuries, it is also widely used in everyday conversation and online.On social media and in online communication, 'accident' can also refer to trouble caused by inappropriate remarks or actions.　　Example:「そのツイート、事故ったな（笑）」" },
        { name: "写メ", description: "A Japanese slang term referring to photos taken with a mobile phone. Originally an abbreviation for 'photo mail,' as it was used to send pictures via email, but now it generally refers to any photo taken with a mobile device.　　Example:「今日のランチの写メ送ってあげるね」" },
        { name: "社畜", description: "A term referring to employees who excessively depend on their company, sacrificing their personal life and health for work. Originally a combination of the words 'society' and 'livestock,' it is used to criticize a lifestyle where one is forced into a work-centric existence, devoting themselves excessively to the company.　　Example:「毎日残業続きで、完全に社畜だわ」" },
        { name: "勝ち確", description: "A term that means 'a state where victory is certain.' It is especially used in competitions, games, or contests when one has an overwhelming advantage over the opponent.　　Example:「この試合、もう勝ち確だね！」" },
        { name: "小動物系", description: "A term used to describe someone with a cute and endearing personality or appearance that makes others want to protect them. It is often used for people who have an innocent, charming, and slightly slow-paced demeanor, resembling a small animal.　　Example:「彼女、小動物系だからみんなに好かれる」" },
        { name: "寝落ち", description: "'Falling asleep unintentionally' or simply 'falling asleep' in casual contexts. 　　Example:「昨日、ゲームしてて寝落ちしちゃった」" },
        { name: "深夜テンション", description: "This term refers to a state of excitement or euphoria that occurs late at night (or in the late hours). It often happens when staying up late, where a person, despite feeling sleepy, becomes strangely energetic or overly excited, acting differently from their usual self.　　Example:「深夜テンションで、友達と突然真剣に宇宙の話をしてた」" },
        { name: "神○○", description: "Originally a religious term referring to deities, this word is now commonly used to describe something or someone that is exceptionally outstanding or beyond the ordinary. For example, when someone's skills or abilities are extremely high, people might say 'god level,' or they might call a favorite person or work 'godly.'　　Example:「彼のゲームプレイ、まさに神だね！」" },
        { name: "親ガチャ", description: "The term refers to how a person's life is significantly influenced by their parents, emphasizing the idea that one cannot choose their parents. It often expresses frustration or resignation toward this reality. The word originates from 'ガチャ' (capsule toy vending machines), where the outcome is random, drawing a parallel to the unpredictability of being born into a certain family.Example:「自分、親ガチャ失敗したな…」" },
        { name: "人をダメにするソファ", description: "This term refers to a sofa that is so incredibly comfortable that once you sit on it, you end up staying there for a long time, unable to move. The extreme relaxation it provides makes the body feel sluggish, leading to the expression 'ダメになる'" },
        { name: "厨二病", description: "This term refers to the exaggerated behavior and self-centered attitude often seen in middle school second-year students (or those around that age). It describes a phase where individuals act as if they are special or different from others, sometimes displaying overly mature speech, dramatic expressions, or indulging in unrealistic fantasies.　　Typical examples include saying overly 'cool' phrases, imagining having unique abilities or a personal worldview, and trying to distinguish themselves from others in an extreme way." },
        { name: "推し", description: "This term refers to a person, character, or artist that someone strongly supports or admires. It is commonly used for idols, actors, anime characters, and game characters. '推し' is more than just liking someone—it implies actively cheering for and supporting them.　　Example:「私の推しはあの俳優です！」" },
        { name: "盛る", description: "This term refers to exaggerating or emphasizing facts.　　Example:「昨日の飲み会、めっちゃ盛って話しちゃったよ（笑）」" },
        { name: "先生", description: "It is used not only for school teachers but also for doctors, lawyers, politicians, calligraphers, and others." },
        { name: "煽り運転", description: "It refers to driving behavior that provokes or angers other drivers. Specifically, it includes actions such as tailgating, repeatedly making sudden lane changes, aggressively overtaking, or driving in an intimidating manner to provoke the other driver.　　Example:「昨日、煽り運転されたんだけど、怖くて焦った」" },
        { name: "全然", description: "It is a word that means 'completely' or 'entirely' and can be used in both positive and negative contexts depending on the situation. Originally, '全然' was used to mean 'entirely' or 'completely,' but in daily conversation, it is often used in negative contexts.　　Negative usage:When used in the form '全然〜ない,' it means 'not at all' or 'not in the slightest.'　Example:「全然眠くない」(Not sleepy at all)　「全然分からない」(Don't understand at all) 　　Positive usage (casual expression):In recent years, it has also been used in positive contexts, similar to 'very' or 'totally.'　Example:「全然美味しい」(Totally delicious)　「全然大丈夫」(Completely fine)" },
        { name: "草", description: "'草' is an internet slang term used to express laughter. It originally comes from the abbreviation 'www,' where the 'w' represents 'warai' (laugh) in Japanese. Example:「あの動画、草生える（笑）」" },
        { name: "台パン", description: "The act of slamming the desk or table with a 'bang' when losing a game or something doesn't go well." },
        { name: "知らんけど", description: "It is a phrase that means 'I don't know' or 'I'm not sure' and is often added at the end of a sentence. This phrase is used in casual conversation when the speaker is uncertain or lacks confidence in what they are saying.　　Example:「あの人、確か明日休みやったと思うけど、知らんけど」" },
        { name: "着メロ", description: "The term refers to the ringtone of a mobile phone." },
        { name: "中華そば", description: "It is ramen, not soba." },
        { name: "朝一", description: "It is an abbreviation for '朝一番(the first thing in the morning).'" },
        { name: "朝ドラ", description: "It is an abbreviation for a Japanese morning TV drama, primarily referring to the serialized dramas broadcast every morning by NHK. The 'Asadora' (morning drama) series, particularly NHK's 'Renjūki Terebi Shōsetsu' (serial TV novels), is famous and is widely watched across Japan by a large audience." },
        { name: "追っかけ", description: "It refers to the act of following and supporting favorite celebrities, artists, idols, etc., by attending their concerts, events, or performances. The English translation could be 'fan following' or 'supporting a favorite celebrity.'　　Example:「昨日、好きなアイドルのライブを追っかけしてきた」" },
        { name: "チン", description: "A casual way to refer to heating something in the microwave. The English translation would be 'microwaving' or 'heating in the microwave.'　　Example:「このお弁当、チンして食べよう」" },
        { name: "難民", description: "The term '難民' (nanmin) originally referred to people displaced due to war, disasters, or other severe circumstances. However, in internet slang or casual usage, it has taken on a lighter meaning. It refers to individuals who are in a difficult situation or facing some kind of trouble, but without the severity of the original meaning. It might be used to describe someone struggling in a more everyday context, such as dealing with a tough situation or feeling overwhelmed by circumstances.　　Example:アニメ難民：A person who wants to watch anime but doesn't know which series to start, or is unable to keep up with the inconsistent airing times.　「最近アニメの新作が多すぎて、どれを見ればいいのかわからない、アニメ難民だ」　　就職難民：A situation where someone is job hunting but is struggling to get a job offer or secure employment.　「就職活動がうまくいかなくて、就職難民になってしまった」" },
        { name: "脳汁", description: "The phrase '脳汁が出る' (noujiru ga deru) refers to the release of neurotransmitters like dopamine and endorphins in the brain when someone experiences excitement or pleasure. It is often used to describe moments of intense enjoyment or exhilaration, such as when listening to favorite music, achieving something significant in a game, or witnessing something entertaining." },
        { name: "飯テロ", description: "'飯テロ' (meshi tero) refers to the phenomenon on social media where someone posts an enticing photo of food, causing others to react by saying things like ' I'm hungry' or ' I want to eat that.' It’s a playful term used when food images 'attack' people’s appetite.　　Example:「昼ご飯のラーメン、めちゃくちゃ美味しそうで飯テロされた！」" },
        { name: "報連相", description: "The abbreviation 'Hō-Ren-Sō' stands for '報告' (report), '連絡' (contact), and '相談' (consultation), which represent the three basic actions of communication in business or organizational settings." },
        { name: "無理", description: "The phrase is used when something feels impossible to achieve or execute. It can also be used to express dislike towards a person, carrying a nuance of 'I don't like you.'　　Example:「あの人まじで無理」(I really don’t like you)" },
        { name: "癒し系", description: "A word that refers to the calm, relaxing impression or atmosphere that people, things, or environments give, creating a sense of peace and tranquility.　　Example:「あの人、癒し系だよね。いつも穏やかで優しい」" },
        { name: "陽キャ", description: "A word that refers to a sociable, cheerful, and extroverted person. The opposite of '陽キャ' (yōkya) is '陰キャ' (inky), which refers to someone with a reserved, introverted, and quiet personality.　　Example:「彼は陽キャだから、パーティーではいつも盛り上げてる」" },
    ];

    const listElement = document.getElementById("list");
    const detailsElement = document.getElementById("details");
    const searchInput = document.getElementById("search");
    let selectedItem = null;

    function updateList(filter = "") {
        listElement.innerHTML = "";
        const filteredItems = items.filter(item => item.name.includes(filter));

        filteredItems.forEach(item => {
            const li = document.createElement("li");
            li.textContent = item.name;

            li.addEventListener("click", () => {
                if (selectedItem) {
                    selectedItem.classList.remove("selected");
                }
                li.classList.add("selected");
                selectedItem = li;

                detailsElement.textContent = `選択: ${item.name} - ${item.description}`;
                detailsElement.style.display = "block";
                detailsElement.style.opacity = "1";
            });

            listElement.appendChild(li);
        });
    }

    searchInput.addEventListener("input", (e) => {
        updateList(e.target.value);
    });

    updateList();
});


